

# ---- configuration ----

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - Submodules
  - node_modules/* # for Netlify bug


timezone  : Asia/Tokyo
encording : utf-8

# ---- gems ----

# ---- collections ----

collections:
  projects :
    output : true
    permlink : /:path

# ---- build option ----

repository: "signalcompose/signalcompose.github.io"


kramdown :
  input : GFM

sass:
  sass_dir : _scss
  style    : compressed
